# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b775fd3773b10f6fc77540141b4a82edc94f38bc04968be4756a506c4af745eab5e493ae35d05c3cbda085d0d0b727a2c046b45e1cb3712a19b1ee34eb5608a

test:
  secret_key_base: fefc14c6b54e395a2eb1803c661d985eaf8f5322241925c45696fa4afd63cd00085f65b16380218b496999e2568b4452a4a552a8a406781868bedf725b362ec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
